### ISSUE TITLE
Streamline the UI

### ISSUE THREAD

**Issue by RinkeHoekstra** [Data2Semantics/Hubble#9]
- Cut away stuff that's not intuitive
- Add a banner + logo (?)
- Add more intuitive labels

**Comment by saramagliacane** [comment]
1. Changed some of the labels (Indication->Diagnosis, Drug-> Drug administration, Overview->Related literature)
2. Added a primitive banner with the D2S logo - probably needs restyling
3. Small modifications in the size of the grids - could be improved

**Comment by LaurensRietveld** [comment]
Just use 1 tab at a time (1 line of code, if we don't like it, comment it out)

**Comment by LaurensRietveld** [comment]
close (other issues take this place)
